"""create initial tables

Revision ID: 32f9108ba4fa
Revises: 
Create Date: 2026-03-08 22:36:11.382207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32f9108ba4fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_users',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='ユーザーID(UUID)'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='ユーザー名'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='メールアドレス'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_m_users_is_deleted'), 'm_users', ['is_deleted'], unique=False)
    op.create_table('m_media_types',
    sa.Column('media_type_id', sa.String(length=36), nullable=False, comment='素材タイプID'),
    sa.Column('media_type_name', sa.String(length=50), nullable=False, comment='素材タイプ名'),
    sa.Column('description', sa.String(length=100), nullable=True, comment='素材タイプの説明'),
    sa.Column('created_user_id', sa.String(length=36), nullable=False, comment='作成者'),
    sa.Column('updated_user_id', sa.String(length=36), nullable=False, comment='更新者'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.ForeignKeyConstraint(['created_user_id'], ['m_users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_user_id'], ['m_users.user_id'], ),
    sa.PrimaryKeyConstraint('media_type_id'),
    sa.UniqueConstraint('media_type_name')
    )
    op.create_index(op.f('ix_m_media_types_is_deleted'), 'm_media_types', ['is_deleted'], unique=False)
    op.create_table('t_content_projects',
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='動画企画ID'),
    sa.Column('project_name', sa.String(length=50), nullable=False, comment='動画企画名'),
    sa.Column('project_summry', sa.Text(), nullable=True, comment='企画概要'),
    sa.Column('created_user_id', sa.String(length=36), nullable=False, comment='作成者'),
    sa.ForeignKeyConstraint(['created_user_id'], ['m_users.user_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('t_media_assets',
    sa.Column('media_asset_id', sa.String(length=36), nullable=False, comment='動画素材ID'),
    sa.Column('media_type_id', sa.String(length=36), nullable=False, comment='素材タイプID'),
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='動画企画ID'),
    sa.Column('original_file_name', sa.String(length=100), nullable=False, comment='アップロードファイル名'),
    sa.Column('saved_file_name', sa.String(length=100), nullable=False, comment='登録ファイル名'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIMEタイプ'),
    sa.Column('storage_path', sa.String(length=1000), nullable=False, comment='保存ストレージパス'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='ファイルサイズ'),
    sa.Column('memo', sa.String(length=1000), nullable=True, comment='メモ'),
    sa.Column('created_user_id', sa.String(length=36), nullable=False, comment='作成者'),
    sa.Column('updated_user_id', sa.String(length=36), nullable=False, comment='更新者'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.ForeignKeyConstraint(['created_user_id'], ['m_users.user_id'], ),
    sa.ForeignKeyConstraint(['media_type_id'], ['m_media_types.media_type_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['t_content_projects.project_id'], ),
    sa.ForeignKeyConstraint(['updated_user_id'], ['m_users.user_id'], ),
    sa.PrimaryKeyConstraint('media_asset_id')
    )
    op.create_index(op.f('ix_t_media_assets_is_deleted'), 't_media_assets', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_media_assets_is_deleted'), table_name='t_media_assets')
    op.drop_table('t_media_assets')
    op.drop_table('t_content_projects')
    op.drop_index(op.f('ix_m_media_types_is_deleted'), table_name='m_media_types')
    op.drop_table('m_media_types')
    op.drop_index(op.f('ix_m_users_is_deleted'), table_name='m_users')
    op.drop_table('m_users')
    # ### end Alembic commands ###
