"""add t_upload_jobs table

Revision ID: a52794e38d07
Revises: 0c41310e5ec1
Create Date: 2026-03-12 19:52:00.418989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a52794e38d07'
down_revision: Union[str, Sequence[str], None] = '0c41310e5ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_upload_jobs',
    sa.Column('job_id', sa.String(length=36), nullable=False, comment='アップロードジョブID'),
    sa.Column('file_name', sa.String(length=100), nullable=False, comment='登録ファイル名'),
    sa.Column('storage_path', sa.String(length=1000), nullable=False, comment='保存ストレージパス'),
    sa.Column('created_user_id', sa.String(length=36), nullable=False, comment='作成者'),
    sa.Column('updated_user_id', sa.String(length=36), nullable=False, comment='更新者'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.ForeignKeyConstraint(['created_user_id'], ['m_users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_user_id'], ['m_users.user_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_t_upload_jobs_is_deleted'), 't_upload_jobs', ['is_deleted'], unique=False)
    op.alter_column('t_media_assets', 'media_type_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True,
               existing_comment='素材タイプID')
    op.alter_column('t_media_assets', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True,
               existing_comment='動画企画ID')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_media_assets', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False,
               existing_comment='動画企画ID')
    op.alter_column('t_media_assets', 'media_type_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False,
               existing_comment='素材タイプID')
    op.drop_index(op.f('ix_t_upload_jobs_is_deleted'), table_name='t_upload_jobs')
    op.drop_table('t_upload_jobs')
    # ### end Alembic commands ###
